# Optional: Mailpit Email Testing Service
# Include this file to enable email testing with Mailpit
# Usage: docker compose -f compose.yaml -f compose.override.yaml -f compose.mailer.yaml up

services:
  mailer:
    image: axllent/mailpit
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_WEB_PORT:-8025}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  php:
    environment:
      # Mailer DSN pointing to the mailpit service
      MAILER_DSN: smtp://mailer:1025